sudo: false
before_install:
- export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$LOCAL
- make
- make install
- cd -
- export PATH="$LOCAL/bin:$PATH"
- export ZSH_CUSTOM="$HOME/.zsh_custom"
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script:
- PATH="./bats/bin:$PATH" bats tests
language: c
